## 1 numpy基本运算

In [2]:
import numpy as np

In [3]:
data = np.random.randn(2,3)
data

array([[-2.29111598,  0.30512202, -1.06682178],
       [ 0.07162219, -0.5542895 ,  0.12418196]])

In [5]:
print(data*10)
print(data+data)

[[-22.91115976   3.0512202  -10.6682178 ]
 [  0.71622188  -5.54289504   1.24181965]]
[[-4.58223195  0.61024404 -2.13364356]
 [ 0.14324438 -1.10857901  0.24836393]]


In [6]:
data.shape

(2, 3)

## 2 创建ndarray

In [7]:
data1 = [6, 7.5, 8, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 1. ])

In [8]:
arr1.ndim

1

In [9]:
arr1.shape

(4,)

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.empty((2, 3, 2))

array([[[1.05162320e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 4.19937310e+175]],

       [[1.42079239e+161, 7.79505948e-043],
        [1.02236860e+166, 6.17186157e-042],
        [2.64521089e+180, 1.22217845e+165]]])

In [14]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 3 ndarray 的数据类型

In [17]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('float64')

In [18]:
arr2.dtype

dtype('int32')

In [19]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [20]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [21]:
arr = np.array([3.7, -1.2, -2.6])
print(arr)
arr.astype(np.int32)

[ 3.7 -1.2 -2.6]


array([ 3, -1, -2])

## 4 Numpy数组的运算

In [22]:
arr = np.array([[1., 2., 3.],[4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [23]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [24]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [26]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [27]:
arr2 = np.array([[0., 4., 1.],[7., 2., 6.]])
arr2 > arr

array([[False,  True, False],
       [ True, False, False]])

## 5 索引和切片

In [31]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr[5]

5

In [33]:
arr[5:8]

array([5, 6, 7])

In [35]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [36]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [37]:
arr_slice[1] = 123456
arr

array([     0,      1,      2,      3,      4,     12, 123456,     12,
            8,      9])

In [40]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(arr2d[2], arr2d[0][2], arr2d[0, 2])

[7 8 9] 3 3


In [45]:
arr3d = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [42]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
arr3d[1,0]

array([7, 8, 9])

## 6 切片索引